### PR TITLE
Add raw output in addition to exr

### PR DESCRIPTION
**Pull request by prabindh**
Added raw output dump in addition to exr. Useful in systems like mine where exr tools are not available.

### CODE REVIEW

**Comment by syoyo** [comment]
You can use tinyexr example to convert exr image to other format.

https://github.com/syoyo/tinyexr/tree/master/examples

**Comment by prabindh** [comment]
Thanks, I did go through that, but it needs an additional step of running tinyexr separately. Just thought that it is simpler to output at the same time as the exr itself.

**Comment by syoyo** [comment]
I guess pfm(portable float map) output is better.

**Comment by syoyo** [comment]
Anyway, merged. Thanks!

**Comment by prabindh** [comment]
Thanks...

**Pull request merged**
