### PR TITLE
Fixies and updates to PBR Surface example

### PR DESCRIPTION
**Pull request by Ybalrid**
Hi,

This PR contains fixes to the pbr_surface example:

- Remove the need to read an external texture to get the ILB environement BRDF (based on the Unreal PBR paper from siggraph 2013 and the khronos "sample" implementation of PBR shader) - texture file got removed as not needed anymore. Regarding the look up table:  Old behavior can be restored by setting `shader.forceBRDFCompute` to `false`, and providing a brdfLUT texture of the resolution of your choice (example: the one from khronos repository). This was a speed optimization for real-time for the original GPU code.
- Fix wrong normal vector reorganization to facevarying order (one of coords got messed up). This was causing strange artifacts in the reflection of the environment map (and probably other harder to see lighting issues)
- Remove macro hack from pbrShader code. This was there because of the port from the original GLSL code.
- Update tinygltf to v2.0 (will output warning messages to cerr, otherwise API was unchanged)
- Various minor code cleaning fixes, spelling fixes
- Updated travis clang version to match tinygltf

### CODE REVIEW

**Comment by syoyo** [comment]
```

**Comment by Ybalrid** [comment]
Oh. I was working on Windows. It builded fine under MSVC...
I'm going to fix that!

**Comment by Ybalrid** [comment]
Can you check with latest commit ?

**Comment by syoyo** [comment]
Thanks! merged.

**Pull request merged**
