### PR TITLE
add example path tracer

### PR DESCRIPTION
**Pull request by daseyb**
Added a path tracing example. Uses a simple specular BRDF with no roughness, but fresnel weighting of specular paths and diffuse reflection vs. transmission parameter.
All material parameters are read from the .mtl file.
Should build fine under Windows with MSVC and Linux with gcc/clang. I don't have access to a Mac, so I couldn't test building on that platform.

### CODE REVIEW

**Comment by syoyo** [comment]
Super cool! Thanks!

**Comment by syoyo** [comment]
FYI, recent tinyobjloader(in devel branch) supports parsing PBR material proposed here: http://exocortex.com/blog/extending_wavefront_mtl_to_support_pbr

**Comment by meshula** [comment]
Parsing PBR, pretty cool :) Have you posted any sample MTL files that show the syntax your parser can accept?

**Comment by syoyo** [comment]
> Have you posted any sample MTL files that show the syntax your parser can accept?

Only unit test data exists so far.

https://github.com/syoyo/tinyobjloader/blob/develop/models/pbr-mat-ext.mtl
https://github.com/syoyo/tinyobjloader/blob/develop/tests/tester.cc#L322

**Comment by meshula** [comment]
Ah great, I see it's exactly as in the excortex page. Thanks for the post.

**Comment by syoyo** [comment]
PR of PBR rendering example(e.g. Disney BRDF) in NanoRT is welcome.

**Pull request merged**
